
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
# tts:
  # - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

homeassistant:
  elevation: 61
  latitude: 32.13520170307117
  name: Home
  longitude: 34.83580112457276
  time_zone: Asia/Jerusalem
  unit_system: metric
  

# hacs:
    # token: 36935147a197055c12576acfe9f9f950f825ad87

logger:
  default: info
  logs:
    custom_components.dynalite: debug
    #homeassistant.components.climate: debug
    homeassistant.components.kodi: debug

dynalite:
  bridges:
    - host: 10.0.0.200
      port: 95
      autodiscover: true
      polltimer: 1
      areacreate: auto
      log_level: debug
      area:
        '7':
          name: Girls Room
          template: room
          channel:
            '1': 
              name: Wall
            '2': 
              name: East
            '3': 
              name: West
        '8':
          name: Master Bedroom
          template: room
          channel:
            '2': 
              name: Ceiling
            '3': 
              name: Wall
            '4': 
              name: Left Reading
            '6': 
              name: Bathroom
        '9':
          name: Office
          template: room
          templateoverride:
            room_on: 1
            room_off: 4
          channel:
            '1': 
              name: Center
            '2': 
              name: East
              fade: 2 # XXX remove, just leave to check
            '3': 
              name: West
        '10':
          name: Cinema
          template: room
          channel:
            '1':
              name: Spot
            '2':
              name: Wall
            '3':
              name: Wall Plug
        '11':
          name: Cinema Bathroom
          template: room
          channel:
            '1':
              name: AAA
        '12':
          name: MAMAD
          template: room
          channel:
            '1': 
              name: MAMAD
              hidden: true
        '13':
          name: Guest Room
          template: room
          channel:
            '1':
              name: Wall
            '2':
              name: Spot
        '16':
          name: Back Garden
          template: room
          channel:
            '1':
              name: Lights
              hidden: true
        '108':
          name: Office Blind
          template: channelcover
          areaoverride: Office
        '110': # Leave one to define explicitly
          name: Cinema Blind
          template: channelcover
          areaoverride: Cinema
        '111':
          name: Guest Room Blind
          template: channelcover
          areaoverride: Guest Room
        '165':
          name: UNKNOWN XXX
          template: hidden
        '170':
          name: UNKNOWN XXX
          template: hidden
        '171':
          name: UNKNOWN XXX
          template: hidden
        '183':
          name: Entrance Gate Internal
          template: hidden
        '184':
          name: Entrance Gate
          template: trigger
        '213':
          name: Cinema Mode
          template: room
      preset:
        '1':
          name: 'On'
          fade: 0
        '4':
          name: 'Off'
          fade: 0
      template:
        'aaa':
          room_on: 2
          room_off: 5
        'room':
          room_off: 4
        'channelcover':
          channel: 2
          class: blind
          factor: 0.73
          tilt: 0.02
      default:
        fade: 0

# media_player:
  # - platform: kodi
    # host: 10.0.0.13
    
# heos:
  # host: 10.0.0.221
  
# climate:
  # - platform: coolmaster
    # host: 10.0.0.20
    # port: 10102
    # supported_modes:
      # - heat
      # - cool
      
# panel_custom:
  # - name: floorplan
    # sidebar_title: Floorplan
    # sidebar_icon: mdi:home
    # url_path: floorplan
    # config: !include floorplan.yaml
    
# frontend:
  # extra_html_url:
    # - /local/custom_ui/state-card-floorplan.html
    
# binary_sensor:
  # - platform: mqtt
    # state_topic: dummy/floorplan/sensor
    # name: Floorplan
    
# homeassistant:
  # customize:    
    # binary_sensor.floorplan:
      # custom_ui_state_card: state-card-floorplan
      # config: !include floorplan.yaml