
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
# tts:
  # - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

homeassistant:
  elevation: 61
  latitude: 32.13520170307117
  name: Home
  longitude: 34.83580112457276
  time_zone: Asia/Jerusalem
  unit_system: metric
  

# hacs:
    # token: 36935147a197055c12576acfe9f9f950f825ad87

logger:
  default: info
  logs:
    custom_components.dynalite: debug
    #homeassistant.components.climate: debug
    homeassistant.components.kodi: debug

dynalite:
  bridges:
    - host: 10.0.0.200
      port: 95
      autodiscover: true
      polltimer: 1
      areacreate: auto
      area:
        '9':
          name: Office
          template: room
          channel:
            '1': 
              name: Center
            '2': 
              name: East
              fade: 2
            '3': 
              name: West
        '10':
          name: Cinema
          channel:
            '1':
              type: switch
              hidden: true
            '3':
        '108':
          name: Office
          nodefault: true
          areaoverride: Office
          channel:
            '2':
              name: Blind
              type: cover
              class: blind
              factor: 0.73
              tilt: 0.02
          preset:
            '1':
              hidden: true
      preset:
        '1':
          name: 'On'
          fade: 0
        '4':
          name: 'Off'
          fade: 0
      template:
        'temp':
          room_on: 2
          room_off: 5
        
          
      default:
        fade: 0

# media_player:
  # - platform: kodi
    # host: 10.0.0.13
    
# heos:
  # host: 10.0.0.221
  
# climate:
  # - platform: coolmaster
    # host: 10.0.0.20
    # port: 10102
    # supported_modes:
      # - heat
      # - cool
      
# panel_custom:
  # - name: floorplan
    # sidebar_title: Floorplan
    # sidebar_icon: mdi:home
    # url_path: floorplan
    # config: !include floorplan.yaml
    
# frontend:
  # extra_html_url:
    # - /local/custom_ui/state-card-floorplan.html
    
# binary_sensor:
  # - platform: mqtt
    # state_topic: dummy/floorplan/sensor
    # name: Floorplan
    
# homeassistant:
  # customize:    
    # binary_sensor.floorplan:
      # custom_ui_state_card: state-card-floorplan
      # config: !include floorplan.yaml